---
name: Ansible collection

'on':
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install yamllint
        run: sudo apt install yamllint
      - name: Lint
        run: yamllint .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Sanity tests with dependencies
        run: ansible-test sanity --requirements --python 3.8
        working-directory: ansible_collections/serverscom/sc_api
      - name: Unit tests with dependencies
        run: ansible-test units --requirements --python 3.8
        working-directory: ansible_collections/serverscom/sc_api
      - name: Try-build by ansible-galaxy
        run: ansible-galaxy collection build
        working-directory: ansible_collections/serverscom/sc_api
